// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SmsApi.Data;

#nullable disable

namespace SmsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521130000_AddFeeStructureIsActive")]
    partial class AddFeeStructureIsActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // BuildTargetModel intentionally minimal — this migration was created manually.
            // The authoritative model snapshot is maintained in AppDbContextModelSnapshot.cs.
            // MigrateAsync() does not call this method; it is only used by `dotnet ef migrations add`.
        }
    }
}
